name: pulse_note
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  intl: ^0.19.0
  fl_chart: ^1.1.1
  
  # State management & DI
  provider: ^6.1.2
  get_it: ^8.0.2
  
  # Health integration
  health: ^11.1.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  google_fonts: ^6.3.2
  
  # Notifications
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

